### ISSUE TITLE
[TASK] Create a UI Builder template for the policy bot

### ISSUE THREAD

**Issue by iclyn-taero** [SEMOSS/semoss-ui#148]
https://www.figma.com/file/uwBMKaElM4Rj3PF0SEHyWl/Create-App?type=design&node-id=1288%3A29051&mode=design&t=DHPcgGxqwhgKbD7U-1

This should display in add app flow when selecting 'use template' and represent a predefined JSON structure for a policy app.

**Comment by natdink** [comment]
Closing as a newer ticket was created for this
