### ISSUE TITLE
[TASK] Listener Settings for blocks show a query status indicator

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#228]
### Description 

Expand on the original issue to talk through what the purpose of the ticket is. 

### Existing

Is there any relevant code or ui feature that the developer should know about when resolving this issue. 

### Reference

This issue references https://github.com/SEMOSS/community/issues/5

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by memisrose** [comment]
Adding small indicators on Run Query listeners:

![image](https://github.com/user-attachments/assets/105fca87-884c-468e-aae9-7450f716d969)
