### ISSUE TITLE
[TASK] Engine name validation check before submision

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#229]
### Description 

Ensure creation of function, database, vector, storage, and model have a validation done before hitting Backend's submission endpoint.  Have the pixel that checks for engine name uniqueness is set on a rule for the form that allows creation (react-hook-form)

### Existing

On our import.constants.ts we have connection options, which is just a list of the fields that are shown per each engine.  
We also have a component called ImportForm 

Each engine form in import.constants should have a name field associated with it.  Per each field, we have rules associated to it.

Pass the reactor as a rule and add in custom logic for rules on the controller to account for the reactor that needs to get called to check the validation.  

https://react-hook-form.com/docs/useform/register#options

### Reference

This issue references. . .

### Tasks

- [] Validation check for engine name uniqueness `CheckEngineName("user input name");;`

**Comment by memisrose** [comment]
This is validation when creating a function, model, database, vector or storage. This is specifically validating the Name (Catalog Name) form field only.
