### ISSUE TITLE
[DES] Update Add Member modal to show additional metadata in search

### ISSUE THREAD

**Issue by natdink** [SEMOSS/semoss-ui#231]
## Problem (Why)

User struggles to add members in the current add member modal because they can only see username in the autocomplete DDL. It is necessary to display other user metadata like email, id and login type in order to know not only which user you are adding but what login for a specific user (i.e. John Doe may have a Native login and a Microsoft login).

## Impact (Who) 

Owners of apps and engines (all users). 

## Existing

An add member modal already exists in Figma. See SEMOSS>Settings>Member & Team Permissions.

## Reference

This issue references https://github.com/SEMOSS/community/issues/16

## Task Suggestions (What)

What are more specific tasks that a designer needs to do to consider this issue resolved 

Consider current design and see if there's an opportunity to refine the UX of how we display the selected users -- currently takes up quite a bit of space.

**Comment by natdink** [comment]
Figma designs are here and ready for review: https://www.figma.com/design/9gIqLnOoJuVQZCDPOrplXa/Member-%26-Team-Permissions?node-id=821-17587&t=8ZunvlnVOYXHuOaT-1

**Comment by neelneelneel** [comment]
Resolved By: #248
