### ISSUE TITLE
[TASK] Ctrl + S saves the app state

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#256]
### Description 

Add shortcut while in edit mode to save the app state.  

- Throw warning to user letting them to know to check there work before saving

### Existing

N/A

### Reference

N/A

### Tasks

-  [x] Add shortcut to save app state
-  [x] After save show notification to user of checking work

**Comment by johbaxter** [comment]
flow goes @SPRCoreDump 

- ctrl +s **saves app
- Notify user "You just saved your app, please ensure that the recent changes you made are accurate", does not have to be word for word, just notify user that they should check their work.

**Comment by protanop1c** [comment]
> flow goes @SPRCoreDump
> 
> * ctrl +s **saves app
> * Notify user "You just saved your app, please ensure that the recent changes you made are accurate", does not have to be word for word, just notify user that they should check their work.

Is there a specific style of notification that's preferred here? I'm assuming a toast or something at the top right with an X is ok since I've seen it elsewhere in the app

**Comment by johbaxter** [comment]
@SPRCoreDump if you look in the code, we have a hook that handles this for us.  All you have to do is call the fn off the hook
