### ISSUE TITLE
[FEAT] Multi-Select Dropdown

### ISSUE THREAD

**Issue by AAfghahi** [SEMOSS/semoss-ui#266]
Description: 

We want the capacity to select multiple options within a dropdown selection menu in the drag and drop app builder select block. 

Existing:

Other applications have this, including the policy vector engine. Furthermore, the MUI dropdown has a built in way of enabling multiple select. 

You could see more here: https://dmp.deloitte.com/detail/video/6345436531112 at the 0:24 to 0:31 timestamp.

**Comment by soumya-pratik** [comment]
This is being developed by @22mayank from USI team.
