### ISSUE TITLE
[TASK] Multifile Upload

### ISSUE THREAD

**Issue by AAfghahi** [SEMOSS/semoss-ui#275]
Description: 

In the Drag and Drop app, we want to be able to upload multiple files at one time. 

Existing: 

This exists in versions of the Policy Vector Engine, please contact Arash to get more details.

**Comment by stelbailey** [comment]
@johbaxter Hello- I have pushed up code for this task in the linked PR, but I have very little experience with the drag & drop app, so I couldn't figure out how to test if it was actually uploading the files to the server. If you could test it and/or show me how to, that would be greatly appreciated. Thanks!
