### ISSUE TITLE
[TASK] Add User modal scroll does not pull next set of users

### ISSUE THREAD

**Issue by themaherkhalil** [SEMOSS/semoss-ui#281]
### Description 

In the app/engine add members where there is the searchable dropdown, if you click and scroll down beyond the initial set of users that appear, there is no additional call made to pull the next set of users.

![image](https://github.com/user-attachments/assets/26bdc616-1f4b-48a3-9a50-1b4ecb576fb9)

### Existing

Is there any relevant code or ui feature that the developer should know about when resolving this issue. 

### Reference

This issue references. . .

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by trevorzylks** [comment]
Tracking for end of week 9/20/2024

**Comment by trevorzylks** [comment]
@johbaxter Believe I have remedied. Are you able to hop on the branch and test as well?

**Comment by johbaxter** [comment]
@trevorzylks will take a look when i can. tied up currently.  In the meantime if he has time ask @JoshRome26 if he has some bandwidth to switch branches to take a look.

I plan on testing, by registering a bunch of new users on your local. and ensuring when i scroll to the bottom of list it makes another pixel call

**Comment by trevorzylks** [comment]
It should do exactly that.

**Comment by trevorzylks** [comment]
<img width="960" alt="image" src="https://github.com/user-attachments/assets/2a256fb5-1228-4903-8a48-3e3e5c94ef88">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/893e8f05-8e43-49d4-b70f-061c9815581d">

**Comment by JoshRome26** [comment]
Will look at this and confirm functionality on my end on 9/20

**Comment by JoshRome26** [comment]
Currently getting an error with the autocomplete that handles the additional reactor calls. Where its not accepting props: "ListboxProps' does not exist on type."

**Comment by johbaxter** [comment]
Needs to fix the TS error, as well as needs to be added to Engine members as well.  Added this in.
