### ISSUE TITLE
[BUG] Admin permissions list display

### ISSUE THREAD

**Issue by saahithisk** [SEMOSS/semoss-ui#310]
### A clear and concise description of what the issue is.
Selecting next refreshes back to the first page of the permission list.

#### How to reproduce the issue

1. Go to any App/Model/Database settings page
2. Click on next page of permission list

### Expected results

View next page in list

### Actual results

List refreshes to show only first page regardless of number of rows displayed

### Screenshots
![image](https://github.com/user-attachments/assets/b96a7373-9e53-4bc8-b8cd-fbdd612ba57e)

### Environment
https://workshop.cfg.deloitte.com/cfg-ai-demo/SemossWeb/packages/client/dist/#/

**Comment by susanta96** [comment]
#296 I tried to fix this same issue on that PR. Please review & let us know...
