### ISSUE TITLE
[DES] Collapsed version of LLM-Cell

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#312]
## Problem (Why)

Create designs for a collapsed version of the llm cell

## Impact (Who) 

Notebook writers

## Existing

![image](https://github.com/user-attachments/assets/ddc387d5-d202-43f7-9ce2-a23a1429384e)

## Reference

N/A

## Task Suggestions (What)

- [] create collapsed version of screenshot from above

**Comment by sarahtrans** [comment]
@kgorbell Link to collapsed llm cell: https://www.figma.com/design/FVOpDpBzTEJxhOtve4Vm2H/LLM-Comparison?node-id=1666-12052&t=xLFabrOrESNCdhSR-1
