### ISSUE TITLE
[TASK] Ensure App Detail Page is accessible for ready only, editor, and author

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/semoss-ui#323]
### Description 

The flow here should mimic similar behavior to our Engine Detail Pages. Add conditional logic for what we have on this so far.

If you have:

No access and its a public app.  
- Able to see Main Uses, Tags, Domain
- Able to Request Access
![image](https://github.com/user-attachments/assets/456cdf0c-1dbe-4ce5-98db-bc8e35ec774f)

Read only access 
- Able to see Main Uses, Tags, Domain not edit
- should be able to change access
- and view all portions of app detail page (no edit)

Editor access
- Able to see Main Uses, Tags, Domain not edit
- should be able to change access
- Able to add members and edit member permission

![image](https://github.com/user-attachments/assets/94052a0e-3bff-41e3-932d-cd4603896e10)

Author Access
- Export App 
- Edit App Details
- Edit Dependencies
- View settings

![image](https://github.com/user-attachments/assets/456cdf0c-1dbe-4ce5-98db-bc8e35ec774f)

### Existing

AppDetailPage.tsx

### Reference

N/A

**Comment by JoshRome26** [comment]
Will try to have this done by Oct 23.
