### ISSUE TITLE
connection_pooling instead of use_connection_pooling property in db connection smss file

### ISSUE THREAD

**Issue by jayesh00949** [SEMOSS/semoss-ui#349]
### Description 

When creating a database connection for both an external database and a PGvector database, and enabling the "Use Connection Pooling" option, the property displayed in the smss file is connection_pooling instead of use_connection_pooling which is expected in backend .

###Steps to reproduce

1.Open cfgai platfrom
2.Click on either open database or open vector.
3.Create a database connection.
4. Check the smss file of the created connection.
5. Observe the property connection_pooling instead of use_connection_pooling

### Reference
![Screenshot (11)](https://github.com/user-attachments/assets/b3e4d5fc-9336-4e2f-a6e6-d92f8581483a)

**Comment by susanta96** [comment]
Let me check & try to make the change from frontend, but make sure backend is expecting USE_CONNECTION_POOLING key right ?

**Comment by susanta96** [comment]
Closing this issue as the fix has been added!!
