### ISSUE TITLE
DRIVER property is missing in PGvector Database smss file

### ISSUE THREAD

**Issue by jayesh00949** [SEMOSS/semoss-ui#350]
### Description 

For enabling "use connection pooling" option in pgvector DB, "DRIVER" property is also needed from smss file which is not getting added in smss file when we are creating a connection.

### Steps to reproduce
1. Open cfgai platfrom
2. Click on open vector.
3. Click on any existing PGvector db or create a new one.
4. After opening the db click on smss.
5. Observe the missing driver property

### Reference

![Screenshot (12)](https://github.com/user-attachments/assets/f6c620b1-9c65-4e28-9f12-8478b2a11ba4)

**Comment by kunal0137** [comment]
Need to pass this during the creation of a vector db
DRIVER  org.postgresql.Driver

**Comment by susanta96** [comment]
Closing the issue, as this got fixed.
