### ISSUE TITLE
Wrong RDBMS_TYPE getting sent for h2 db

### ISSUE THREAD

**Issue by jayesh00949** [SEMOSS/semoss-ui#352]
### Description 

While creating a h2 db connection in cfgai app we are getting an error, upon checking the call in network tab it was found that RDBMS_TYPE is getting sent as "HIVE" which should be "H2_DB"

### Steps to reproduce
1.Open cfgai platform
2.Click on "open database"
3.Click on "Add Database"
4.Click on H2 db under connections
5. Enter details of H2 DB and click on "create database"
6. An error will appear on the screen.

### Reference

![Screenshot (14)](https://github.com/user-attachments/assets/8906f702-248e-4c90-9749-5ff6e9b8a1a3)
![Screenshot (15)](https://github.com/user-attachments/assets/62b1ce69-d604-42ca-a39b-fd4829b3ee4b)

### Tasks

RDBMS_TYPE should be changed to H2_DB for H2 db

**Comment by kunal0137** [comment]
add in the driver as well - org.h2.Driver
